animal = ['bear','python','peacock','kangaroo','whale','platypus']

print "The animal at 1 is the 2nd animal and is a %r." % animal[1]
print "The 3rd animal is at 2 and is a %r." % animal[2]
print "The 1st animal is at 0 and is a %r." % animal[0]
print "The animal at 3 is the 4th animal and is a %r." % animal[3]
print "The 5th animal is at 4 and is a %r." % animal[4]
print "The animal at 2 is the 3rd animal and is a %r." % animal[2]
print "The 6th animal is at 5 and is a %r." % animal[5]
print "The animal at 4 is the 5th animal and is a %r." % animal[4]
